import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import Navbar from "@/components/navbar/page";
import Footer from "@/components/footer/page";
import { Toaster } from "react-hot-toast";
import CartContextProvider from "@/components/context/CartContext";
import { SessionProvider } from "next-auth/react";
import MySessionProvider from "@/components/MYSessionProvider/MySessionProvider";
import WishContextProvider from "@/components/context/WishContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shop mart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

 
   <MySessionProvider>
    <CartContextProvider>
      <WishContextProvider>
    <Navbar/>
       <div className="container mx-auto ">
        
          {children}
           <Toaster />
       </div>
       <Footer/>
       </WishContextProvider>
 </CartContextProvider>
   </MySessionProvider>
      </body>
    </html>
  );
}
